global using DotNet8.AuditLogMiniProject.Infrastructure.Interceptors;
global using DotNet8.AuditLogMiniProject.Infrastructure;
global using Microsoft.EntityFrameworkCore;
global using DotNet8.AuditLogMiniProject.Domain.Features.Blog;
global using DotNet8.AuditLogMiniProject.Infrastructure.Features.Blog;
global using DotNet8.AuditLogMiniProject.Shared;
global using Microsoft.AspNetCore.Mvc;
global using DotNet8.AuditLogMiniProject.DTOs.Features.Blog;
global using DotNet8.AuditLogMiniProject.Presentation.Dependencies;
